# ---------------------
# THEME (Remote theme is supported by GitHub Pages)
# ---------------------
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "contrast"

# ---------------------
# SITE SETTINGS
# ---------------------
locale: "en-US"
title: "Testing Branch"
name: "Miguel Batista"
tagline: "ML experiments, simulations & privacy metrics"
title_separator: " | "
description: "Explorations in machine learning, simulation, anonymization, and data modeling â€” practical notebooks and experiments."
url: "https://www.testingbranch.com"
baseurl: ""
repository: "mpcsb/testing_branch"

logo: "/assets/images/logo.png"
words_per_minute: 150

# ---------------------
# FOOTER
# ---------------------
footer:
  show_powered_by: false

# ---------------------
# SEARCH
# ---------------------
search: true
search_full_content: true
search_provider: lunr

# ---------------------
# SEO + SOCIAL
# ---------------------
og_image: "/assets/images/logo.png"

twitter:
  username: mpcbatista

social:
  type: Person
  name: "Miguel Batista"
  links:
    - "https://github.com/mpcsb/"
    - "https://twitter.com/mpcbatista/"
    - "https://linkedin.com/in/miguelcbatista/"

# ---------------------
# PAGINATION
# ---------------------
paginate: 6
paginate_path: "/page:num/"

# ---------------------
# COLLECTIONS
# ---------------------
collections:
  drafts:
    output: false
    permalink: /:categories/:title/

# ---------------------
# MARKDOWN
# ---------------------
markdown: kramdown
highlighter: rouge

# ---------------------
# PERMALINKS
# ---------------------
permalink: /:categories/:title/

# ---------------------
# DEFAULTS
# ---------------------
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: false
      share: true
      related: true
